// <auto-generated />
using System;
using System.Collections.Generic;
using LatexView.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LatexView.Bot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128035914_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LatexView.Bot.Models.CompileRequest", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<long>("ResultMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("result_message_id");

                    b.Property<DateTimeOffset>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Options", "LatexView.Bot.Models.CompileRequest.Options#CompileRequestOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("UsePdfAVersion");

                            b1
                                .ToJson("options")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("UserId", "MessageId");

                    b.ToTable("compile_request", (string)null);
                });

            modelBuilder.Entity("LatexView.Bot.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("LatexView.Bot.Models.CompileRequest", b =>
                {
                    b.HasOne("LatexView.Bot.Models.User", "User")
                        .WithMany("CompileRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LatexView.Bot.Models.User", b =>
                {
                    b.Navigation("CompileRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
